-- ============================================================
-- Briefing, Academy & Market Drivers
-- ============================================================

-- Daily news briefing (generated by Claude daily)
create table if not exists public.daily_briefing (
  id         uuid primary key default gen_random_uuid(),
  date       date unique not null,
  sections   jsonb not null default '[]', -- [{icon, title, summary, callout, source}]
  glossary   jsonb not null default '[]', -- [{term, definition}]
  pdf_url    text,
  created_at timestamptz not null default now()
);

create index if not exists idx_briefing_date on public.daily_briefing(date desc);

alter table public.daily_briefing enable row level security;

drop policy if exists "Authenticated users can read briefings" on public.daily_briefing;
create policy "Authenticated users can read briefings"
  on public.daily_briefing for select
  to authenticated using (true);

drop policy if exists "Service role can insert briefings" on public.daily_briefing;
create policy "Service role can insert briefings"
  on public.daily_briefing for insert
  to service_role with check (true);

drop policy if exists "Service role can update briefings" on public.daily_briefing;
create policy "Service role can update briefings"
  on public.daily_briefing for update
  to service_role using (true);

-- ============================================================

-- Academy learning terms (generated by Claude daily, curated paths)
create table if not exists public.learning_terms (
  id            uuid primary key default gen_random_uuid(),
  date          date not null,
  learning_path text not null check (learning_path in ('finance_fundamentals', 'immobilienfinanzierung', 'makrooekonomie')),
  term          text not null,
  definition    text not null,
  example       text not null,
  created_at    timestamptz not null default now()
);

create index if not exists idx_terms_path_date on public.learning_terms(learning_path, date desc);

alter table public.learning_terms enable row level security;

drop policy if exists "Authenticated users can read terms" on public.learning_terms;
create policy "Authenticated users can read terms"
  on public.learning_terms for select
  to authenticated using (true);

drop policy if exists "Service role can insert terms" on public.learning_terms;
create policy "Service role can insert terms"
  on public.learning_terms for insert
  to service_role with check (true);

-- ============================================================

-- Per-user learning progress (spaced repetition)
create table if not exists public.term_progress (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid references auth.users(id) on delete cascade not null,
  term_id       uuid references public.learning_terms(id) on delete cascade not null,
  status        text not null default 'new' check (status in ('new', 'learning', 'mastered')),
  last_reviewed date,
  review_count  int not null default 0,
  unique(user_id, term_id)
);

create index if not exists idx_progress_user on public.term_progress(user_id);

alter table public.term_progress enable row level security;

drop policy if exists "Users manage own progress" on public.term_progress;
create policy "Users manage own progress"
  on public.term_progress for all
  to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ============================================================

-- Daily market drivers snapshot (structured JSON, no prose)
create table if not exists public.market_drivers_snapshot (
  id              uuid primary key default gen_random_uuid(),
  date            date unique not null,
  zins_countdown  jsonb, -- {fed_date, ezb_date, fed_consensus, ezb_consensus}
  makro_kalender  jsonb, -- [{event, date, previous, expected}]
  earnings_watch  jsonb, -- [{company, date, expected_eps}]
  sentiment_ampel jsonb, -- {vix, level, label}
  geo_risiko      jsonb, -- [{region, status}]
  created_at      timestamptz not null default now()
);

create index if not exists idx_snapshot_date on public.market_drivers_snapshot(date desc);

alter table public.market_drivers_snapshot enable row level security;

drop policy if exists "Authenticated users can read snapshots" on public.market_drivers_snapshot;
create policy "Authenticated users can read snapshots"
  on public.market_drivers_snapshot for select
  to authenticated using (true);

drop policy if exists "Service role can insert snapshots" on public.market_drivers_snapshot;
create policy "Service role can insert snapshots"
  on public.market_drivers_snapshot for insert
  to service_role with check (true);

drop policy if exists "Service role can update snapshots" on public.market_drivers_snapshot;
create policy "Service role can update snapshots"
  on public.market_drivers_snapshot for update
  to service_role using (true);
